//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AveragingService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountActivity
    {
        public System.Guid Id { get; set; }
        public short YearOf { get; set; }
        public long RegDate { get; set; }
        public int RegTime { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public short TransactionType { get; set; }
        public long Numerator { get; set; }
        public decimal Balance { get; set; }
        public System.Guid AccountId { get; set; }
        public int RegBranchId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
