//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AveragingService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountActivities = new HashSet<AccountActivity>();
            this.YearAccounts = new HashSet<YearAccount>();
        }
    
        public System.Guid Id { get; set; }
        public int IndexNo { get; set; }
        public int GeneralNo { get; set; }
        public long AccountNo { get; set; }
        public decimal Balance { get; set; }
        public string Description { get; set; }
        public int BranchId { get; set; }
    
        public virtual ICollection<AccountActivity> AccountActivities { get; set; }
        public virtual ICollection<YearAccount> YearAccounts { get; set; }
    }
}
