//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AveragingService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayIndexAccount
    {
        public System.Guid Id { get; set; }
        public int GeneralNo { get; set; }
        public int IndexNo { get; set; }
        public long RegDate { get; set; }
        public decimal DayBalance { get; set; }
        public decimal DayDebtor { get; set; }
        public decimal DayDeposit { get; set; }
        public int DayActivityCount { get; set; }
        public int DayOpenedCount { get; set; }
    }
}
