//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AveragingService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearAccount
    {
        public System.Guid Id { get; set; }
        public int YearOf { get; set; }
        public decimal Balance { get; set; }
        public decimal Debtor { get; set; }
        public decimal Creditor { get; set; }
        public System.Guid AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
